/*
 * Safety net for legacy page copy. New interactive copy should still use
 * useI18n().tr(), but this keeps every hard-coded label, modal, table heading,
 * placeholder, and server alert Arabic while the document is in Arabic mode.
 */
const ar: Record<string, string> = {
  "Cairo, Egypt": "القاهرة، مصر",
  "Preparing Talk & TASTE…": "جارٍ تجهيز Talk & TASTE…",
  "Close menu": "إغلاق القائمة",
  "Collapse sidebar": "طي القائمة الجانبية",
  "Close navigation": "إغلاق التنقل",
  "Open menu": "فتح القائمة",
  "Dismiss error": "إغلاق التنبيه",
  "Show password": "إظهار كلمة المرور",
  "Hide password": "إخفاء كلمة المرور",
  Accountability: "المساءلة",
  "A tamper-evident view of sensitive actions across this branch.": "عرض موثوق للإجراءات الحساسة في هذا الفرع.",
  "Export log": "تصدير السجل",
  "Financial activity cannot be silently deleted": "لا يمكن حذف النشاط المالي دون أثر",
  "Voids, discounts, receipt reprints, stock changes, logins, and manual drawer openings are recorded with the employee, device, time, and values.": "تُسجّل عمليات الإلغاء والخصومات وإعادة طباعة الإيصالات وتغييرات المخزون وتسجيلات الدخول وفتح الدرج يدوياً مع الموظف والجهاز والوقت والقيم.",
  "Search activity, user, or order": "ابحث في النشاط أو الموظف أو الطلب",
  Device: "الجهاز",
  Reference: "المرجع",
  Change: "التغيير",
  Admin: "الإدارة",
  "Previous value saved": "تم حفظ القيمة السابقة",
  "New record": "سجل جديد",
  "New value saved": "تم حفظ القيمة الجديدة",
  "State changed": "تغيّرت الحالة",
  "Multi-branch control": "إدارة الفروع",
  "Distinct branch identities, devices, and revocable credentials.": "هويات مستقلة للفروع والأجهزة وبيانات اعتماد قابلة للإلغاء.",
  "Add branch": "إضافة فرع",
  "Create and edit branches on the cloud website. This Windows installation can only adopt a cloud branch using its one-time code in Settings.": "أنشئ الفروع وعدّلها من موقع السحابة. لا يستطيع تثبيت ويندوز إلا الارتباط بفرع سحابي باستخدام الرمز لمرة واحدة من الإعدادات.",
  staff: "موظفون",
  Branch: "الفرع",
  Code: "الرمز",
  "Last seen": "آخر اتصال",
  Status: "الحالة",
  "Create an independent cafe location.": "أنشئ موقع مقهى مستقلاً.",
  "Branch code": "رمز الفرع",
  "English name": "الاسم بالإنجليزية",
  Address: "العنوان",
  Phone: "الهاتف",
  "Receipt information": "بيانات الإيصال",
  Notes: "ملاحظات",
  "Create branch": "إنشاء الفرع",
  "Edit branch": "تعديل الفرع",
  "changes are audited and synchronized.": "التغييرات مسجلة وتتم مزامنتها.",
  "Branch enabled": "الفرع مفعّل",
  "Disabled branches cannot be used for new deployments.": "لا يمكن استخدام الفروع المعطلة في تثبيتات جديدة.",
  "Save branch": "حفظ الفرع",
  Copy: "نسخ",
  "Use once on the branch computer": "يُستخدم مرة واحدة على كمبيوتر الفرع",
  "and cannot be reused.": "ولا يمكن استخدامه مرة أخرى.",
  Done: "تم",
  "No address added": "لم يُضف عنوان",
  "Local device": "جهاز محلي",
  "Front Counter": "الكاشير الأمامي",
  Revoke: "إلغاء",
  Restore: "استعادة",
  "Relationships & credit": "العملاء والائتمان",
  "Manage approved credit accounts and customer balances.": "إدارة حسابات الائتمان المعتمدة وأرصدة العملاء.",
  "Add customer": "إضافة عميل",
  "Total customers": "إجمالي العملاء",
  "Credit approved": "ائتمان معتمد",
  "Outstanding credit": "الائتمان المستحق",
  "Search customers": "ابحث عن عميل",
  Contact: "بيانات الاتصال",
  Available: "المتاح",
  Since: "منذ",
  History: "السجل",
  Payment: "الدفع",
  "Create a customer and optional credit account.": "أنشئ عميلاً وحساب ائتمان اختياري.",
  "Full name": "الاسم الكامل",
  Email: "البريد الإلكتروني",
  "Approve customer credit": "اعتماد ائتمان العميل",
  "Allows “pay later” sales up to the limit.": "يسمح بالمبيعات الآجلة حتى الحد المحدد.",
  "Credit limit (EGP)": "حد الائتمان (ج.م)",
  "Create customer": "إنشاء العميل",
  "Record credit payment": "تسجيل دفعة ائتمان",
  owes: "مدين بمبلغ",
  "Amount (EGP)": "المبلغ (ج.م)",
  "Payment method": "طريقة الدفع",
  Cash: "نقدي",
  cash: "نقدي",
  card: "بطاقة",
  credit: "آجل",
  sale: "بيع",
  "Walk-in": "عميل نقدي",
  "Card / Visa": "بطاقة / فيزا",
  "Record payment": "تسجيل الدفعة",
  Outstanding: "المستحق",
  "Historical purchases": "المشتريات السابقة",
  Transactions: "المعاملات",
  "Customer notes": "ملاحظات العميل",
  "Save notes": "حفظ الملاحظات",
  Time: "الوقت",
  Order: "الطلب",
  Total: "الإجمالي",
  "Previous payments": "الدفعات السابقة",
  Method: "الطريقة",
  Amount: "المبلغ",
  "Remote branch monitor": "مراقبة الفروع عن بُعد",
  "Near-real-time sales, money, stock, staff, credit, shift, and audit activity": "متابعة شبه فورية للمبيعات والأموال والمخزون والموظفين والائتمان والورديات والمراجعة",
  sales: "مبيعات",
  "active shifts": "ورديات نشطة",
  "stock events": "أحداث مخزون",
  "staff events": "أحداث موظفين",
  "treasury events": "أحداث خزينة",
  "customer credit": "ائتمان العملاء",
  "audit events": "أحداث مراجعة",
  refunds: "مرتجعات",
  voids: "إلغاءات",
  stock: "مخزون",
  audit: "مراجعة",
  "Stock control": "إدارة المخزون",
  "Live quantities, adjustments, and a complete movement trail.": "كميات مباشرة وتعديلات وسجل كامل للحركات.",
  "Add ingredient": "إضافة مكوّن",
  "Tracked products": "المنتجات المتتبعة",
  "Stock value": "قيمة المخزون",
  "Packaged stock": "مخزون المنتجات المعبأة",
  Ingredients: "المكوّنات",
  "Movement history": "سجل الحركات",
  "Branch transfers": "التحويلات بين الفروع",
  "Search stock": "ابحث في المخزون",
  SKU: "رمز الصنف",
  "Unit cost": "تكلفة الوحدة",
  retail: "بيع",
  units: "وحدات",
  Ingredient: "المكوّن",
  Unit: "الوحدة",
  "Current stock": "المخزون الحالي",
  "Low at": "حد التنبيه",
  "Estimated value": "القيمة التقديرية",
  Item: "الصنف",
  Movement: "الحركة",
  "Before → After": "قبل ← بعد",
  "Outgoing transfers": "التحويلات الصادرة",
  Dispatched: "تم الإرسال",
  Destination: "الوجهة",
  Quantity: "الكمية",
  User: "الموظف",
  Reason: "السبب",
  "Received transfers": "التحويلات المستلمة",
  Received: "تم الاستلام",
  Source: "المصدر",
  Current: "الحالي",
  "Movement type": "نوع الحركة",
  "Stock receipt": "استلام مخزون",
  "Manual adjustment": "تعديل يدوي",
  Wastage: "هالك",
  Damaged: "تالف",
  "Branch transfer": "تحويل فرع",
  "Destination branch": "الفرع الوجهة",
  "Select another branch": "اختر فرعاً آخر",
  "Required for the audit trail": "مطلوب لسجل المراجعة",
  "New quantity": "الكمية الجديدة",
  "Create a measured raw-material stock item.": "أنشئ صنف مخزون لمادة خام بوحدة قياس.",
  "Measurement unit": "وحدة القياس",
  grams: "جرام",
  kilograms: "كيلوجرام",
  milliliters: "ملليلتر",
  liters: "لتر",
  pieces: "قطعة",
  "Opening quantity": "الكمية الافتتاحية",
  "Low-stock alert": "تنبيه انخفاض المخزون",
  "Cost per": "التكلفة لكل",
  "Create ingredient": "إنشاء المكوّن",
  "(EGP)": "(ج.م)",
  "Sales & accountability": "المبيعات والمساءلة",
  "Every completed, changed, and voided transaction in one place.": "كل معاملة مكتملة أو معدلة أو ملغاة في مكان واحد.",
  "Export report": "تصدير التقرير",
  "Search order or customer": "ابحث عن طلب أو عميل",
  discount: "خصم",
  refunded: "مسترد",
  "No transactions found": "لا توجد معاملات",
  "Sales from this branch will appear here.": "ستظهر مبيعات هذا الفرع هنا.",
  "Transaction details": "تفاصيل المعاملة",
  Items: "الأصناف",
  each: "للوحدة",
  "Activity history": "سجل النشاط",
  Reprint: "إعادة الطباعة",
  Refund: "استرداد",
  "Void order": "إلغاء الطلب",
  "Reason for": "سبب",
  "Required for the audit log": "مطلوب لسجل المراجعة",
  Confirm: "تأكيد",
  workspace: "مساحة العمل",
  "This module is connected to the same permission-aware Admin shell and will be completed on top of the current local-first data model.": "هذه الوحدة متصلة بنظام الإدارة والصلاحيات نفسه وتعتمد نموذج البيانات المحلي الحالي.",
  "Branch-local changes": "تغييرات محلية للفرع",
  "Full audit trail": "سجل مراجعة كامل",
  "Cloud sync ready": "جاهز للمزامنة السحابية",
  "products available": "منتجات متاحة",
  Only: "متبقي فقط",
  "Sold out": "نفد المخزون",
  Disabled: "معطّل",
  "Choose a payment method": "اختر طريقة الدفع",
  "items in this order": "أصناف في هذا الطلب",
  items: "أصناف",
  "+ Add": "+ إضافة",
  "Cash received": "المبلغ المستلم",
  EGP: "ج.م",
  "Change due": "الباقي",
  "Use the card terminal": "استخدم جهاز البطاقة",
  "Confirm the terminal payment, then complete this sale.": "أكد الدفع على جهاز البطاقة ثم أتمم البيع.",
  "Select an approved customer": "اختر عميلاً معتمداً",
  available: "متاح",
  "Payment complete": "تم الدفع",
  "Order #": "طلب رقم",
  Barista: "مقدم الطلب",
  "Customer balance": "رصيد العميل",
  "New order": "طلب جديد",
  "Held orders": "الطلبات المعلّقة",
  "Resume an order without losing its history.": "استأنف طلباً دون فقد سجله.",
  "No held orders": "لا توجد طلبات معلّقة",
  "Choose an option": "اختر خياراً",
  "Processing…": "جارٍ التنفيذ…",
  all: "الكل",
  completed: "مكتمل",
  voided: "ملغي",
  held: "معلّق",
  Open: "مفتوح",
  "Close shift": "إغلاق الوردية",
  "Open shift": "فتح الوردية",
  "Catalog management": "إدارة قائمة المنتجات",
  "Bilingual products, categories, pricing, and stock behavior.": "منتجات وفئات ثنائية اللغة مع الأسعار وإعدادات المخزون.",
  Category: "الفئة",
  "Add product": "إضافة منتج",
  "Active products": "المنتجات النشطة",
  Categories: "الفئات",
  "Stock tracked": "متابعة المخزون",
  Products: "المنتجات",
  "Search catalog": "ابحث في القائمة",
  Cost: "التكلفة",
  "Profit / margin": "الربح / الهامش",
  "estimated margin": "هامش تقديري",
  "Edit product": "تعديل المنتج",
  products: "منتجات",
  "Edit category": "تعديل الفئة",
  "SKU · optional": "رمز الصنف · اختياري",
  "Select category": "اختر الفئة",
  "Barcode · optional": "الباركود · اختياري",
  "Description · optional": "الوصف · اختياري",
  "Price (EGP)": "السعر (ج.م)",
  "Cost (EGP)": "التكلفة (ج.م)",
  "Opening stock": "المخزون الافتتاحي",
  "Low-stock alert at": "تنبيه انخفاض المخزون عند",
  "Product symbol": "رمز المنتج",
  "Card color": "لون البطاقة",
  "Track finished-product stock": "تتبّع مخزون المنتج النهائي",
  "Useful for Pepsi, chips, and packaged products.": "مفيد للمشروبات والوجبات الخفيفة والمنتجات المعبأة.",
  "Advanced · variants and estimated usage": "متقدم · الخيارات والاستهلاك التقديري",
  "Link the base product or its options to ingredients for automatic theoretical consumption.": "اربط المنتج أو خياراته بالمكوّنات لحساب الاستهلاك النظري تلقائياً.",
  "Base ingredient · optional": "المكوّن الأساسي · اختياري",
  "No automatic consumption": "لا يوجد استهلاك تلقائي",
  "Base estimated usage": "الاستهلاك الأساسي التقديري",
  "Base usage unit": "وحدة الاستهلاك الأساسية",
  "Internal notes": "ملاحظات داخلية",
  "Available at branches": "متاح في الفروع",
  Option: "الخيار",
  Remove: "إزالة",
  "Ingredient · optional": "المكوّن · اختياري",
  "Variant SKU · optional": "رمز الخيار · اختياري",
  "Price EGP": "السعر ج.م",
  "Cost EGP": "التكلفة ج.م",
  "Est. usage": "الاستهلاك التقديري",
  "Track stock for this option": "تتبّع مخزون هذا الخيار",
  "Overrides the shared product stock when enabled.": "يستخدم مخزوناً مستقلاً عن المنتج عند تفعيله.",
  "Option opening stock": "المخزون الافتتاحي للخيار",
  "Option low-stock alert": "تنبيه انخفاض مخزون الخيار",
  "Add variant": "إضافة خيار",
  "Product available for sale": "المنتج متاح للبيع",
  "Disabled products remain in historical reports.": "تبقى المنتجات المعطلة في التقارير السابقة.",
  "Category available for sale": "الفئة متاحة للبيع",
  "Disabling preserves historical transactions.": "التعطيل يحافظ على المعاملات السابقة.",
  "Accent color": "اللون المميز",
  "Financial visibility": "الرؤية المالية",
  "Synchronized multi-branch sales and operations in EGP.": "مبيعات وعمليات الفروع المتزامنة بالجنيه المصري.",
  "All branches": "كل الفروع",
  "Export CSV": "تصدير ملف",
  "% estimated margin": "٪ هامش تقديري",
  Today: "اليوم",
  Yesterday: "أمس",
  "This week": "هذا الأسبوع",
  "Last week": "الأسبوع الماضي",
  "This month": "هذا الشهر",
  "Last month": "الشهر الماضي",
  All: "الكل",
  Employee: "الموظف",
  "All employees": "كل الموظفين",
  "All payments": "كل طرق الدفع",
  Card: "بطاقة",
  Credit: "آجل",
  Product: "المنتج",
  "All products": "كل المنتجات",
  "All categories": "كل الفئات",
  Customer: "العميل",
  "All customers": "كل العملاء",
  From: "من",
  To: "إلى",
  "Apply custom range": "تطبيق النطاق المخصص",
  "Net sales": "صافي المبيعات",
  "Completed transactions": "المعاملات المكتملة",
  Orders: "الطلبات",
  average: "المتوسط",
  Discounts: "الخصومات",
  "Permission-controlled": "حسب الصلاحية",
  "Estimated gross profit": "إجمالي الربح التقديري",
  "Selling price less item cost": "سعر البيع ناقص تكلفة الصنف",
  "Cost of goods": "تكلفة البضاعة",
  "Historical cost snapshots": "تكاليف محفوظة وقت البيع",
  "After recorded expenses": "بعد المصروفات المسجلة",
  "Gross profit less expenses": "إجمالي الربح ناقص المصروفات",
  "Revenue trend": "اتجاه الإيرادات",
  "Payment mix": "توزيع طرق الدفع",
  "Revenue by tender": "الإيراد حسب طريقة الدفع",
  "Product performance": "أداء المنتجات",
  "Revenue and estimated margin by product": "الإيراد والهامش التقديري حسب المنتج",
  "Units sold": "الوحدات المباعة",
  Revenue: "الإيراد",
  "Gross profit": "إجمالي الربح",
  Margin: "الهامش",
  "Category sales": "مبيعات الفئات",
  "Units and revenue by menu group": "الوحدات والإيراد حسب مجموعة القائمة",
  Share: "النسبة",
  "Estimated ingredient consumption": "الاستهلاك التقديري للمكوّنات",
  "Theoretical usage calculated from sold products and variants": "الاستهلاك النظري المحسوب من المنتجات والخيارات المباعة",
  "Estimated · recorded wastage/damage": "تقديري · الهالك/التالف المسجل",
  "No recipe-linked sales in this period.": "لا توجد مبيعات مرتبطة بوصفات في هذه الفترة.",
  "Employee performance": "أداء الموظفين",
  "Transaction count and sales for the selected period": "عدد المعاملات والمبيعات للفترة المحددة",
  "Average transaction": "متوسط المعاملة",
  "Customer credit": "ائتمان العملاء",
  "Outstanding accounts and repayments": "الحسابات المستحقة والسداد",
  "Customers owing": "العملاء المدينون",
  "Payments received": "الدفعات المستلمة",
  "Payment count": "عدد الدفعات",
  "Operational controls": "الرقابة التشغيلية",
  "Exceptions and recorded costs": "الاستثناءات والتكاليف المسجلة",
  "Voided transactions": "المعاملات الملغاة",
  Refunds: "المرتجعات",
  Expenses: "المصروفات",
  "Audit events": "أحداث المراجعة",
  "Branch comparison": "مقارنة الفروع",
  "Combined or selected branch performance": "أداء الفروع مجتمعة أو المحددة",
  Average: "المتوسط",
  "Shift closing differences": "فروقات إغلاق الورديات",
  "Saved shortages and excesses for the period": "العجز والزيادة المسجلان للفترة",
  Closed: "مغلق",
  Expected: "المتوقع",
  Actual: "الفعلي",
  Difference: "الفرق",
  "Treasury by movement": "الخزينة حسب الحركة",
  "Money in and out": "الأموال الداخلة والخارجة",
  "Inventory movements": "حركات المخزون",
  "Physical stock activity": "نشاط المخزون الفعلي",
  events: "أحداث",
  "Branch configuration": "إعدادات الفرع",
  "Safe defaults for this local branch installation.": "إعدادات آمنة لهذا التثبيت المحلي.",
  Business: "النشاط التجاري",
  "Tax & receipt": "الضريبة والإيصال",
  "Cloud sync": "المزامنة السحابية",
  Security: "الأمان",
  "Business identity": "هوية النشاط التجاري",
  "Shown throughout Admin, POS, and printed receipts.": "تظهر في الإدارة ونقطة البيع والإيصالات المطبوعة.",
  "Brand name": "اسم العلامة التجارية",
  "Primary currency": "العملة الأساسية",
  "Egyptian Pound — EGP": "الجنيه المصري — ج.م",
  "Business timezone": "المنطقة الزمنية للنشاط",
  "Tax configuration": "إعداد الضريبة",
  "VAT is disabled by default and can be enabled when required.": "ضريبة القيمة المضافة معطلة افتراضياً ويمكن تفعيلها عند الحاجة.",
  "Enable VAT": "تفعيل ضريبة القيمة المضافة",
  "Apply configured tax rules to new transactions.": "تطبيق قواعد الضريبة على المعاملات الجديدة.",
  "VAT rate (%)": "نسبة الضريبة (%)",
  "Prices include VAT": "الأسعار تشمل الضريبة",
  "Do not add tax above the menu price.": "لا تضف الضريبة فوق سعر القائمة.",
  "Receipt & cash drawer": "الإيصال ودرج النقدية",
  "Thermal print behavior and bilingual receipt content.": "إعدادات الطباعة الحرارية ومحتوى الإيصال ثنائي اللغة.",
  "Receipt footer / message": "تذييل / رسالة الإيصال",
  "Auto-print after checkout": "الطباعة تلقائياً بعد البيع",
  "Opens the system print dialog after a successful sale.": "يفتح نافذة الطباعة بعد نجاح البيع.",
  "Arabic & English capable": "يدعم العربية والإنجليزية",
  "Uses the active POS language and RTL layout.": "يستخدم لغة نقطة البيع واتجاه العرض المناسب.",
  "Show branch": "إظهار الفرع",
  "Include branch identity on each receipt.": "إضافة هوية الفرع إلى كل إيصال.",
  "Drawer trigger": "تشغيل الدرج",
  "Via receipt printer": "عبر طابعة الإيصالات",
  "Browser / local bridge": "المتصفح / الموصل المحلي",
  "Cloud synchronization": "المزامنة السحابية",
  "Branch-local sales continue even when this service is unavailable.": "تستمر مبيعات الفرع محلياً حتى عند تعذر هذه الخدمة.",
  "This installation is paired": "هذا التثبيت مرتبط بالسحابة",
  "All queued branch data has been uploaded.": "تم رفع كل بيانات الفرع المنتظرة.",
  "Sync retries automatically whenever internet is available.": "تُعاد محاولة المزامنة تلقائياً عند توفر الإنترنت.",
  "Offline local mode": "الوضع المحلي دون إنترنت",
  "Sales and all other work stay safely on this computer. You can operate for weeks, then pair once and upload the complete queued history to its cloud branch.": "تبقى المبيعات وكل الأعمال محفوظة على هذا الكمبيوتر. يمكنك العمل لأسابيع ثم الربط مرة واحدة ورفع السجل الكامل إلى فرعه السحابي.",
  "One-time cloud pairing code": "رمز الربط السحابي لمرة واحدة",
  "Cloud Admin → Branches → Pair Windows": "لوحة السحابة ← الفروع ← ربط ويندوز",
  "Pair this installation": "ربط هذا التثبيت",
  "Pairing…": "جارٍ الربط…",
  "Security controls": "ضوابط الأمان",
  "Enforced by the branch server for every request.": "يفرضها خادم الفرع على كل طلب.",
  "Live permissions and immutable accountability": "صلاحيات فورية ومساءلة غير قابلة للمحو",
  "Staff deactivation and permission changes apply immediately. Passwords and PINs are hashed, login attempts are rate-limited, and sensitive actions are recorded in the synchronized audit trail.": "يُطبق تعطيل الموظفين وتغيير الصلاحيات فوراً. تُشفّر كلمات المرور والأرقام السرية، وتُحد محاولات الدخول، وتُسجل الإجراءات الحساسة في سجل المراجعة المتزامن.",
  "Access & payroll control": "إدارة الصلاحيات والرواتب",
  "Permissions, employment records, activity, and the yellow notebook in one place.": "الصلاحيات وبيانات التوظيف والنشاط ودفتر الحسابات في مكان واحد.",
  "Add employee": "إضافة موظف",
  "Create secure branch access and an employment record.": "أنشئ دخولاً آمناً للفرع وسجلاً وظيفياً.",
  "Employment start": "تاريخ بدء العمل",
  "Monthly salary (EGP)": "الراتب الشهري (ج.م)",
  Owner: "المالك",
  "Temporary password": "كلمة مرور مؤقتة",
  "Create employee": "إنشاء الموظف",
  "Permissions remain individually editable.": "تبقى الصلاحيات قابلة للتعديل بشكل منفرد.",
  "Role name": "اسم الدور",
  "Base role": "الدور الأساسي",
  "Assigned branch": "الفرع المعيّن",
  "Entry type": "نوع القيد",
  "Effective date": "تاريخ السريان",
  "Reason / note": "السبب / الملاحظة",
  "Side Counter": "الكاشير الجانبي",
  CAI02: "مثال: CAI02",
  "Active staff": "الموظفون النشطون",
  "Permission sets": "مجموعات الصلاحيات",
  "Available permissions": "الصلاحيات المتاحة",
  Employees: "الموظفون",
  "Roles & permissions": "الأدوار والصلاحيات",
  "more permissions": "صلاحيات إضافية",
  "granted permissions": "صلاحيات ممنوحة",
  "Edit role": "تعديل الدور",
  "Create a custom role": "إنشاء دور مخصص",
  "Start with no access, then assign permissions individually.": "ابدأ بلا صلاحيات ثم عيّنها بشكل منفرد.",
  "Current branch": "الفرع الحالي",
  "No role · configure individually": "بلا دور · إعداد منفرد",
  "Use at least 10 characters.": "استخدم ١٠ أحرف على الأقل.",
  "Manage access": "إدارة الصلاحيات",
  "No base role": "بلا دور أساسي",
  "Save access": "حفظ الصلاحيات",
  Role: "الدور",
  Salary: "الراتب",
  "Profile & ledger": "الملف والحسابات",
  Access: "الصلاحيات",
  "Remaining salary": "الراتب المتبقي",
  "Monthly sales": "مبيعات الشهر",
  "Days worked": "أيام العمل",
  "Save employment": "حفظ بيانات التوظيف",
  "Cash handled": "النقد المتداول",
  "Discounts given": "الخصومات الممنوحة",
  "Voids / refunds": "الإلغاءات / المرتجعات",
  "Drawer openings": "مرات فتح الدرج",
  "Audit events shown": "أحداث المراجعة المعروضة",
  "Yellow notebook entry": "قيد دفتر الحسابات",
  "Salary advance": "سلفة راتب",
  Deduction: "خصم",
  Bonus: "مكافأة",
  "Salary payment": "دفع راتب",
  "Employee owes business": "الموظف مدين للنشاط",
  "Business owes employee": "النشاط مدين للموظف",
  "Leave / absence": "إجازة / غياب",
  "Add ledger entry": "إضافة قيد حساب",
  calculation: "الحساب",
  "Base salary": "الراتب الأساسي",
  "Bonuses / owed": "المكافآت / المستحق",
  "Advances / deductions": "السلف / الخصومات",
  Paid: "المدفوع",
  Remaining: "المتبقي",
  Date: "التاريخ",
  Type: "النوع",
  Note: "الملاحظة",
  "Recorded by": "سجله",
  "Recent activity": "النشاط الأخير",
  Cancel: "إلغاء",
  Custom: "مخصص",
  "God user / Owner": "المالك / المدير العام",
  "Money movement": "حركة الأموال",
  "Sales, voids, expenses, and tender totals for this branch.": "المبيعات والإلغاءات والمصروفات وإجماليات الدفع لهذا الفرع.",
  Expense: "مصروف",
  "Net recorded movement": "صافي الحركة المسجلة",
  "Recent movements": "أحدث الحركات",
  "Recorded automatically from branch activity": "مسجلة تلقائياً من نشاط الفرع",
  Description: "الوصف",
  "Saved shift closings": "إغلاقات الورديات المحفوظة",
  "Historical drawer reconciliation and tender breakdown": "تسوية الدرج السابقة وتفصيل طرق الدفع",
  Shift: "الوردية",
  "Cash / Card / Credit": "نقدي / بطاقة / آجل",
  "Record expense": "تسجيل مصروف",
  "Creates a treasury movement and audit event.": "ينشئ حركة خزينة وحدث مراجعة.",
  Supplies: "مستلزمات",
  Utilities: "مرافق",
  Maintenance: "صيانة",
  Transport: "نقل",
  Other: "أخرى",
  "Paid by": "طريقة الدفع",
  "Manual treasury movement": "حركة خزينة يدوية",
  "Owner deposits, supplier payments, withdrawals, and other money.": "إيداعات المالك ومدفوعات الموردين والمسحوبات والأموال الأخرى.",
  Direction: "الاتجاه",
  "Money in": "أموال داخلة",
  "Money out": "أموال خارجة",
  "Owner deposit": "إيداع المالك",
  "Other income": "دخل آخر",
  "Supplier payment": "دفع مورد",
  Withdrawal: "سحب",
  "Stock purchase": "شراء مخزون",
  Miscellaneous: "متنوع",
  "Attachment reference · optional": "مرجع المرفق · اختياري",
  "Receipt URL or file reference": "رابط الإيصال أو مرجع الملف",
  "Record movement": "تسجيل الحركة",
  "Counted cash (EGP)": "النقد المعدود (ج.م)",
  "Closing note": "ملاحظة الإغلاق",
  "Reconcile & close": "تسوية وإغلاق",
  "Expected cash": "النقد المتوقع",
  "This result and your note are permanently recorded in the audit log.": "تُسجل هذه النتيجة وملاحظتك نهائياً في سجل المراجعة.",
  "Open shift with EGP 0": "فتح وردية برصيد ٠ ج.م",
  "Count the physical cash in the drawer.": "عُدّ النقد الفعلي الموجود في الدرج.",
  "voids ·": "إلغاءات ·",
  "refunds (": "مرتجعات (",
  "discounts ·": "خصومات ·",
  expenses: "مصروفات",
  "added · −": "مضاف · −",
  removed: "مسحوب",
  "Enter the complete code shown in Cloud Admin.": "أدخل الرمز الكامل الظاهر في لوحة السحابة.",
  "Pairing failed": "فشل الربط",
  "Something went wrong": "حدث خطأ ما",
  "A customer is required for credit sales": "يجب اختيار عميل للبيع الآجل",
  "A non-empty order and open shift are required": "يلزم طلب غير فارغ ووردية مفتوحة",
  "A refund reason is required": "سبب الاسترداد مطلوب",
  "A selected product is no longer available": "أحد المنتجات المحددة لم يعد متاحاً",
  "A selected product option is no longer available": "أحد خيارات المنتج لم يعد متاحاً",
  "A valid amount and payment method are required": "يلزم مبلغ صحيح وطريقة دفع",
  "A valid closing cash count is required": "يلزم إدخال قيمة صحيحة للنقد عند الإغلاق",
  "A void reason is required": "سبب الإلغاء مطلوب",
  "An open shift is required": "يلزم وجود وردية مفتوحة",
  "Bilingual names and a valid price are required": "يلزم الاسمان العربي والإنجليزي وسعر صحيح",
  "Bilingual role names are required": "يلزم اسم الدور بالعربية والإنجليزية",
  "Branch code already exists": "رمز الفرع موجود مسبقاً",
  "Branch not found": "الفرع غير موجود",
  "Branch not found or disabled": "الفرع غير موجود أو معطّل",
  "Branch, code, and name are required": "الفرع والرمز والاسم مطلوبة",
  "Branches are created in Cloud Admin, then paired to Windows": "تُنشأ الفروع من لوحة السحابة ثم تُربط بويندوز",
  "Branches are managed in Cloud Admin": "تُدار الفروع من لوحة السحابة",
  "Built-in roles cannot be modified": "لا يمكن تعديل الأدوار الأساسية",
  "Category names cannot be blank": "لا يمكن ترك أسماء الفئة فارغة",
  "Category not found": "الفئة غير موجودة",
  "Category, bilingual names, and a valid price are required": "تلزم الفئة والاسمان العربي والإنجليزي وسعر صحيح",
  "Category, description, amount, and payment method are required": "تلزم الفئة والوصف والمبلغ وطريقة الدفع",
  "Cloud receiver is not enabled": "استقبال السحابة غير مفعّل",
  "Cloud returned an incomplete branch identity": "أعادت السحابة هوية فرع غير مكتملة",
  "Cloud servers cannot be paired": "لا يمكن ربط خادم السحابة كفرع",
  "Code and bilingual names are required": "يلزم الرمز والاسمان العربي والإنجليزي",
  "Credit limit must be a non-negative EGP amount": "يجب أن يكون حد الائتمان مبلغاً غير سالب بالجنيه",
  "Customer credit limit would be exceeded": "ستتجاوز العملية حد ائتمان العميل",
  "Customer is not approved for credit": "العميل غير معتمد للشراء الآجل",
  "Customer name is required": "اسم العميل مطلوب",
  "Customer not found": "العميل غير موجود",
  "Destination branch not found or disabled": "الفرع الوجهة غير موجود أو معطّل",
  "Direction, movement type, amount, payment method, and notes are required": "يلزم الاتجاه ونوع الحركة والمبلغ وطريقة الدفع والملاحظات",
  "Discount cannot exceed subtotal": "لا يمكن أن يتجاوز الخصم المجموع الفرعي",
  "Discount permission is required": "صلاحية الخصم مطلوبة",
  "Each variant requires bilingual names and a valid price": "كل خيار يحتاج اسماً عربياً وإنجليزياً وسعراً صحيحاً",
  "Email already exists": "البريد الإلكتروني موجود مسبقاً",
  "Username already exists": "اسم المستخدم موجود مسبقاً",
  "Email and password are required": "البريد الإلكتروني وكلمة المرور مطلوبان",
  "User and password are required": "المستخدم وكلمة المرور مطلوبان",
  "Employee not found": "الموظف غير موجود",
  "Enable the branch before pairing": "فعّل الفرع قبل الربط",
  "English and Arabic names are required": "الاسمان العربي والإنجليزي مطلوبان",
  "Enter a cloud pairing code": "أدخل رمز الربط السحابي",
  "Enter a valid pairing code": "أدخل رمز ربط صحيحاً",
  "Held order contains an unavailable option": "الطلب المعلّق يحتوي خياراً غير متاح",
  "Held order contains an unavailable product": "الطلب المعلّق يحتوي منتجاً غير متاح",
  "Held order not found": "الطلب المعلّق غير موجود",
  "Ingredient SKU already exists at this branch": "رمز المكوّن موجود مسبقاً في هذا الفرع",
  "Ingredient not found": "المكوّن غير موجود",
  "Ingredient unit mismatch": "وحدة قياس المكوّن غير متطابقة",
  "Insufficient ingredient stock for transfer": "مخزون المكوّن لا يكفي للتحويل",
  "Insufficient stock for transfer": "المخزون لا يكفي للتحويل",
  "Invalid branch credentials": "بيانات اعتماد الفرع غير صحيحة",
  "Invalid checkout": "بيانات البيع غير صحيحة",
  "Invalid opening cash": "قيمة النقد الافتتاحي غير صحيحة",
  "Invalid synchronization event": "حدث المزامنة غير صحيح",
  "Inventory item not found": "صنف المخزون غير موجود",
  "Item, another destination branch, positive quantity, and reason are required": "يلزم الصنف وفرع وجهة آخر وكمية موجبة وسبب",
  "Names, email, and a password of at least 10 characters are required": "تلزم الأسماء والبريد وكلمة مرور من ١٠ أحرف على الأقل",
  "Names, username, and a password of at least 10 characters are required": "تلزم الأسماء واسم المستخدم وكلمة مرور من ١٠ أحرف على الأقل",
  "No editable fields supplied": "لم تُرسل حقول قابلة للتعديل",
  "Not found": "غير موجود",
  "Only an unrefunded completed order can be refunded": "يمكن استرداد طلب مكتمل وغير مسترد فقط",
  "Only completed orders can be voided": "يمكن إلغاء الطلبات المكتملة فقط",
  "Open shift not found": "لم توجد وردية مفتوحة",
  "Order not found": "الطلب غير موجود",
  "Owner setup is already complete": "اكتمل إعداد المالك مسبقاً",
  "Packaged-product transfer quantity must be a whole number": "يجب أن تكون كمية تحويل المنتج المعبأ عدداً صحيحاً",
  "Pairing code expired": "انتهت صلاحية رمز الربط",
  "Pairing code is invalid": "رمز الربط غير صحيح",
  "Pairing code was already used": "استُخدم رمز الربط مسبقاً",
  "Pairing codes are created on the cloud server": "تُنشأ رموز الربط على خادم السحابة",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "Payment exceeds the outstanding balance": "الدفعة تتجاوز الرصيد المستحق",
  "Permission denied": "ليست لديك الصلاحية المطلوبة",
  "Product not found": "المنتج غير موجود",
  "Quantity and reason are required": "الكمية والسبب مطلوبان",
  "Role name already exists": "اسم الدور موجود مسبقاً",
  "Role names cannot be blank": "لا يمكن ترك أسماء الدور فارغة",
  "Role not found": "الدور غير موجود",
  "SKU already exists": "رمز الصنف موجود مسبقاً",
  "SKU, bilingual names, and a supported unit are required": "يلزم رمز الصنف والاسمان العربي والإنجليزي ووحدة مدعومة",
  "Salary must be a non-negative EGP amount": "يجب أن يكون الراتب مبلغاً غير سالب بالجنيه",
  "Selected ingredient was not found": "المكوّن المحدد غير موجود",
  "Session user is disabled": "مستخدم الجلسة معطّل",
  "Session user not found": "مستخدم الجلسة غير موجود",
  "Stock cannot become negative": "لا يمكن أن يصبح المخزون سالباً",
  "Stock, low-stock level, and unit cost cannot be negative": "لا يمكن أن يكون المخزون أو حد التنبيه أو تكلفة الوحدة سالباً",
  "Super Admin access cannot be reduced": "لا يمكن تقليل صلاحيات المدير العام",
  "Tax rate must be between 0 and 100": "يجب أن تكون نسبة الضريبة بين ٠ و١٠٠",
  "The active session branch cannot disable itself": "لا يمكن للفرع النشط تعطيل نفسه",
  "The cloud pairing endpoint must use HTTPS": "يجب أن يستخدم عنوان الربط السحابي HTTPS",
  "This installation is already paired": "هذا التثبيت مرتبط مسبقاً",
  "Tracked product not found": "المنتج المتتبّع غير موجود",
  "Type, non-negative amount, and note are required": "يلزم النوع ومبلغ غير سالب وملاحظة",
  "Unknown permission": "صلاحية غير معروفة",
  "Unsupported setting": "إعداد غير مدعوم",
  "Use an owner password between 12 and 128 characters": "استخدم كلمة مرور للمالك بين ١٢ و١٢٨ حرفاً",
  "User not found": "المستخدم غير موجود",
  "Variant not found": "الخيار غير موجود",
  "Variant usage unit must match the selected ingredient": "يجب أن تطابق وحدة استهلاك الخيار وحدة المكوّن المحدد",
  "Save business settings": "حفظ إعدادات النشاط",
  "Save tax settings": "حفظ إعدادات الضريبة",
  "Save receipt settings": "حفظ إعدادات الإيصال",
  "auth login": "تسجيل الدخول",
  "auth logout": "تسجيل الخروج",
  "branch created": "إنشاء فرع",
  "branch paired": "ربط فرع",
  "branch pairing_code_created": "إنشاء رمز ربط للفرع",
  "branch updated": "تحديث فرع",
  "cash_drawer opened": "فتح درج النقدية",
  "category created": "إنشاء فئة",
  "category updated": "تحديث فئة",
  "customer created": "إنشاء عميل",
  "customer credit_payment": "تسجيل دفعة ائتمان للعميل",
  "customer updated": "تحديث عميل",
  "expense created": "إنشاء مصروف",
  "ingredient_stock adjusted": "تعديل مخزون مكوّن",
  "inventory adjusted": "تعديل المخزون",
  "inventory transfer_dispatched": "إرسال تحويل مخزون",
  "inventory_item created": "إنشاء صنف مخزون",
  "order completed": "إكمال طلب",
  "order held": "تعليق طلب",
  "order held_cancelled": "إلغاء طلب معلّق",
  "order refunded": "استرداد طلب",
  "order resumed": "استئناف طلب",
  "order voided": "إلغاء طلب",
  "item added": "إضافة صنف",
  "item removed": "إزالة صنف",
  "item quantity_changed": "تغيير كمية صنف",
  "discount changed": "تغيير الخصم",
  "payment changed": "تغيير طريقة الدفع",
  "note changed": "تغيير الملاحظة",
  "product created": "إنشاء منتج",
  "product updated": "تحديث منتج",
  "receipt reprinted": "إعادة طباعة إيصال",
  "role created": "إنشاء دور",
  "role updated": "تحديث دور",
  "settings updated": "تحديث الإعدادات",
  "setup owner_created": "إنشاء حساب المالك",
  "shift closed": "إغلاق وردية",
  "shift opened": "فتح وردية",
  "staff created": "إنشاء موظف",
  "staff employment_updated": "تحديث بيانات التوظيف",
  "staff ledger_entry_created": "إنشاء قيد حساب موظف",
  "staff permissions_changed": "تغيير صلاحيات موظف",
  "staff salary_modified": "تعديل راتب موظف",
  "treasury movement_created": "إنشاء حركة خزينة",
  "variant created": "إنشاء خيار منتج",
  "variant updated": "تحديث خيار منتج",
  "Full system access": "صلاحية كاملة للنظام",
  POS: "نقطة البيع",
  Sales: "المبيعات",
  Reports: "التقارير",
  Treasury: "الخزينة",
  Inventory: "المخزون",
  Staff: "الموظفون",
  Customers: "العملاء",
  Branches: "الفروع",
  Audit: "المراجعة",
  Shifts: "الورديات",
  Payroll: "الرواتب",
  Settings: "الإعدادات",
  access: "دخول",
  view: "عرض",
  manage: "إدارة",
  daily: "يومي",
  financial: "مالي",
  drawer: "الدرج",
  reprint: "إعادة طباعة",
  void: "إلغاء",
  "Unable to sign in": "تعذر تسجيل الدخول",
  "Unable to finish setup": "تعذر إكمال الإعداد",
  "Invalid email or password": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  "Invalid user or password": "المستخدم أو كلمة المرور غير صحيحة",
  "Manual POS open": "فتح يدوي لنقطة البيع",
  "Internal server error": "خطأ داخلي في الخادم",
  "Cash drawer hardware bridge is not configured": "خدمة درج النقدية غير مهيأة على جهاز ويندوز",
  "The cash drawer could not be opened": "تعذر فتح درج النقدية",
};

const patterns: Array<[RegExp, (...parts: string[]) => string]> = [
  [/^(\d+) local changes are safely queued for upload\.$/, (n) => `${n} تغييرات محلية محفوظة بانتظار الرفع.`],
  [/^(\d+) changes will retry automatically\.$/, (n) => `ستُعاد محاولة ${n} تغييرات تلقائياً.`],
  [/^(\d+) products available$/, (n) => `${n} منتجات متاحة`],
  [/^Only (\d+) left$/, (n) => `متبقي ${n} فقط`],
  [/^(\d+) items in this order$/, (n) => `${n} أصناف في هذا الطلب`],
  [/^(\d+) items$/, (n) => `${n} أصناف`],
  [/^(\d+) units$/, (n) => `${n} وحدات`],
  [/^(\d+) staff$/, (n) => `${n} موظفين`],
  [/^(\d+) permissions$/, (n) => `${n} صلاحيات`],
  [/^Shift opened by (.+)$/, (name) => `فتح الوردية: ${name}`],
  [/^Reason for (.+)$/, (action) => `سبب ${translateArabic(action)}`],
  [/^user:(.+)$/, (id) => `مستخدم:${id}`],
  [/^held_order:(.+)$/, (id) => `طلب معلّق:${id}`],
  [/^role:(.+)$/, (id) => `دور:${id}`],
  [/^Cash checkout (.+)$/, (order) => `دفع نقدي ${order}`],
  [/^Hardware bridge returned (\d+)$/, (status) => `تعذر فتح درج النقدية (خطأ الجهاز ${status})`],
];

export function translateArabic(value: string): string {
  const trimmed = value.trim();
  if (!trimmed || !/[A-Za-z]/.test(trimmed)) return value;
  const exact = ar[trimmed];
  let translated = exact;
  if (!translated) {
    for (const [pattern, render] of patterns) {
      const match = trimmed.match(pattern);
      if (match) {
        translated = render(...match.slice(1));
        break;
      }
    }
  }
  if (!translated) return value;
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  return `${leading}${translated}${trailing}`;
}

type TextState = { source: string; rendered: string };
const textState = new WeakMap<Text, TextState>();
const attributeState = new WeakMap<Element, Map<string, TextState>>();
const attributes = ["placeholder", "title", "aria-label"];

function excluded(node: Node) {
  const element = node instanceof Element ? node : node.parentElement;
  return Boolean(element?.closest("[data-no-localize],script,style,code"));
}

function localizeText(node: Text, arabic: boolean) {
  if (excluded(node)) return;
  const current = node.nodeValue ?? "";
  const previous = textState.get(node);
  if (arabic) {
    const source = previous && current === previous.rendered ? previous.source : current;
    const rendered = translateArabic(source);
    textState.set(node, { source, rendered });
    if (current !== rendered) node.nodeValue = rendered;
  } else if (previous) {
    if (current === previous.rendered) node.nodeValue = previous.source;
    textState.delete(node);
  }
}

function localizeElement(element: Element, arabic: boolean) {
  if (excluded(element)) return;
  let states = attributeState.get(element);
  if (!states) {
    states = new Map();
    attributeState.set(element, states);
  }
  for (const name of attributes) {
    const current = element.getAttribute(name);
    if (current === null) continue;
    const previous = states.get(name);
    if (arabic) {
      const source = previous && current === previous.rendered ? previous.source : current;
      const rendered = translateArabic(source);
      states.set(name, { source, rendered });
      if (current !== rendered) element.setAttribute(name, rendered);
    } else if (previous) {
      if (current === previous.rendered) element.setAttribute(name, previous.source);
      states.delete(name);
    }
  }
}

function walk(root: Node, arabic: boolean) {
  if (root instanceof Text) localizeText(root, arabic);
  if (root instanceof Element) localizeElement(root, arabic);
  const walker = document.createTreeWalker(
    root,
    NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT,
  );
  let node = walker.nextNode();
  while (node) {
    if (node instanceof Text) localizeText(node, arabic);
    else if (node instanceof Element) localizeElement(node, arabic);
    node = walker.nextNode();
  }
}

export function localizeDocument(language: "en" | "ar") {
  const arabic = language === "ar";
  walk(document.body, arabic);
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "characterData") localizeText(mutation.target as Text, arabic);
      else if (mutation.type === "attributes") localizeElement(mutation.target as Element, arabic);
      else mutation.addedNodes.forEach((node) => walk(node, arabic));
    }
  });
  observer.observe(document.body, {
    subtree: true,
    childList: true,
    characterData: true,
    attributes: true,
    attributeFilter: attributes,
  });
  return () => observer.disconnect();
}
