import { useEffect, useState, type FormEvent } from "react";
import { BadgeCheck, CircleDollarSign, History, Plus, Save, Search, UserRound, UsersRound, X } from "lucide-react";
import { formatMoney } from "@token-taste/shared";
import { api } from "../api";
import { useAuth } from "../auth";
import { useI18n } from "../i18n";
import { StatusBadge } from "../components/StatusBadge";

type Customer = { id: string; name: string; phone: string; email: string; notes:string; credit_approved: number; credit_limit: number; credit_balance: number; active: number; created_at: string;historical_purchases?:number;last_transaction?:string };
type CustomerProfile={customer:Customer;transactions:Array<{id:string;order_number:string;total:number;payment_method:string;status:string;created_at:string}>;payments:Array<{id:string;amount:number;payment_method:string;description:string;created_at:string}>};

export function CustomersPage() {
  const { can } = useAuth();
  const { language, t } = useI18n();
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", email: "", creditApproved: false, creditLimit: 0 });
  const [paymentCustomer, setPaymentCustomer] = useState<Customer | null>(null);
  const [payment, setPayment] = useState({ amount: 0, paymentMethod: "cash" });
  const [profile,setProfile]=useState<CustomerProfile|null>(null); const [profileNotes,setProfileNotes]=useState("");
  const load = () => api<{ customers: Customer[] }>("/api/customers").then((data) => setCustomers(data.customers));
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); await api("/api/customers", { method: "POST", body: JSON.stringify({ ...form, creditLimit: form.creditLimit * 100 }) }); setOpen(false); setForm({ name: "", phone: "", email: "", creditApproved: false, creditLimit: 0 }); await load(); };
  const recordPayment = async (event: FormEvent) => { event.preventDefault(); if (!paymentCustomer) return; await api(`/api/customers/${paymentCustomer.id}/payment`, { method: "POST", body: JSON.stringify({ amount: Math.round(payment.amount * 100), paymentMethod: payment.paymentMethod }) }); setPaymentCustomer(null); setPayment({ amount: 0, paymentMethod: "cash" }); await load(); };
  const openProfile=async(customer:Customer)=>{const detail=await api<CustomerProfile>(`/api/customers/${customer.id}/profile`);setProfile(detail);setProfileNotes(detail.customer.notes??"");};
  const saveProfile=async()=>{if(!profile)return;await api(`/api/customers/${profile.customer.id}`,{method:"PATCH",body:JSON.stringify({notes:profileNotes})});await openProfile(profile.customer);await load();};
  const filtered = customers.filter((customer) => `${customer.name} ${customer.phone} ${customer.email}`.toLowerCase().includes(search.toLowerCase()));
  const totalCredit = customers.reduce((sum, customer) => sum + customer.credit_balance, 0);
  return <div className="content-page">
    <div className="page-heading"><div><span className="eyebrow">Relationships & credit</span><h2>{t("customers")}</h2><p>Manage approved credit accounts and customer balances.</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={18}/ > Add customer</button></div>
    <div className="mini-metrics"><article><span><UsersRound /></span><div><small>Total customers</small><strong>{customers.length}</strong></div></article><article><span className="success"><BadgeCheck /></span><div><small>Credit approved</small><strong>{customers.filter((customer) => customer.credit_approved).length}</strong></div></article><article><span className="warning"><CircleDollarSign /></span><div><small>Outstanding credit</small><strong>{formatMoney(totalCredit, language)}</strong></div></article></div>
    <section className="panel table-panel"><div className="table-toolbar"><label><Search size={18}/><input placeholder="Search customers" value={search} onChange={(event) => setSearch(event.target.value)}/></label></div><div className="table-wrap"><table><thead><tr><th>{t("customer")}</th><th>Contact</th><th>{t("creditBalance")}</th><th>{t("creditLimit")}</th><th>Available</th><th>{t("status")}</th><th/></tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id}><td><div className="person-cell"><span>{customer.name.slice(0, 2).toUpperCase()}</span><div><strong>{customer.name}</strong><small>Since {new Date(customer.created_at).toLocaleDateString()}</small></div></div></td><td>{customer.phone || "—"}<small>{customer.email}</small></td><td><strong>{formatMoney(customer.credit_balance, language)}</strong></td><td>{formatMoney(customer.credit_limit, language)}</td><td>{formatMoney(Math.max(0, customer.credit_limit - customer.credit_balance), language)}</td><td><StatusBadge value={customer.credit_approved ? "Credit approved" : "Cash only"}/></td><td><div className="heading-actions"><button className="soft-button small" onClick={()=>void openProfile(customer)}>History</button>{customer.credit_balance>0&&can("credit.manage")&&<button className="soft-button small" onClick={()=>{setPaymentCustomer(customer);setPayment({amount:customer.credit_balance/100,paymentMethod:"cash"});}}>Payment</button>}</div></td></tr>)}</tbody></table></div></section>
    {open && <div className="modal-backdrop"><form className="modal compact-modal" onSubmit={submit}><header><div><span><UserRound /></span><div><h2>Add customer</h2><p>Create a customer and optional credit account.</p></div></div><button type="button" className="icon-button" onClick={() => setOpen(false)}><X/></button></header><label className="field"><span>Full name</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><div className="field-row"><label className="field"><span>Phone</span><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })}/></label><label className="field"><span>Email</span><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/></label></div><label className="switch-field"><input type="checkbox" checked={form.creditApproved} onChange={(event) => setForm({ ...form, creditApproved: event.target.checked })}/><i/><div><strong>Approve customer credit</strong><small>Allows “pay later” sales up to the limit.</small></div></label>{form.creditApproved && <label className="field"><span>Credit limit (EGP)</span><input type="number" min="0" value={form.creditLimit || ""} onChange={(event) => setForm({ ...form, creditLimit: Number(event.target.value) })}/></label>}<div className="modal-actions"><button type="button" className="soft-button" onClick={() => setOpen(false)}>{t("cancel")}</button><button className="primary-button">Create customer</button></div></form></div>}
    {paymentCustomer&&<div className="modal-backdrop"><form className="modal compact-modal" onSubmit={recordPayment}><header><div><span><CircleDollarSign/></span><div><h2>Record credit payment</h2><p>{paymentCustomer.name} · owes {formatMoney(paymentCustomer.credit_balance,language)}</p></div></div><button type="button" className="icon-button" onClick={()=>setPaymentCustomer(null)}><X/></button></header><div className="field-row"><label className="field"><span>Amount (EGP)</span><input type="number" min="0.01" max={paymentCustomer.credit_balance/100} step="0.01" required value={payment.amount||""} onChange={e=>setPayment({...payment,amount:Number(e.target.value)})}/></label><label className="field"><span>Payment method</span><select value={payment.paymentMethod} onChange={e=>setPayment({...payment,paymentMethod:e.target.value})}><option value="cash">Cash</option><option value="card">Card / Visa</option></select></label></div><div className="modal-actions"><button type="button" className="soft-button" onClick={()=>setPaymentCustomer(null)}>{t("cancel")}</button><button className="primary-button">Record payment</button></div></form></div>}
    {profile&&<div className="modal-backdrop"><section className="modal permission-modal customer-profile"><header><div><span><History/></span><div><h2>{profile.customer.name}</h2><p>{profile.customer.phone||"No phone"} · {profile.customer.credit_approved?"Credit account":"Cash account"}</p></div></div><button className="icon-button" onClick={()=>setProfile(null)}><X/></button></header><div className="mini-metrics"><article><span><CircleDollarSign/></span><div><small>Outstanding</small><strong>{formatMoney(profile.customer.credit_balance,language)}</strong></div></article><article><span className="success"><BadgeCheck/></span><div><small>Historical purchases</small><strong>{formatMoney(profile.customer.historical_purchases??0,language)}</strong></div></article><article><span className="warning"><History/></span><div><small>Transactions</small><strong>{profile.transactions.length}</strong></div></article></div><label className="field"><span>Customer notes</span><textarea rows={2} value={profileNotes} onChange={e=>setProfileNotes(e.target.value)}/></label><button className="soft-button small profile-save" onClick={saveProfile}><Save/> Save notes</button><div className="customer-history-grid"><section><h3>Transactions</h3><div className="table-wrap"><table><thead><tr><th>Time</th><th>Order</th><th>Payment</th><th>Total</th></tr></thead><tbody>{profile.transactions.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.order_number}<small>{item.status}</small></td><td className="capitalize">{item.payment_method}</td><td>{formatMoney(item.total,language)}</td></tr>)}</tbody></table></div></section><section><h3>Previous payments</h3><div className="table-wrap"><table><thead><tr><th>Time</th><th>Method</th><th>Amount</th></tr></thead><tbody>{profile.payments.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleDateString()}</td><td className="capitalize">{item.payment_method}</td><td>{formatMoney(item.amount,language)}</td></tr>)}</tbody></table></div></section></div></section></div>}
  </div>;
}
